action_emb: scratch
alpha_body: null
alpha_root: null
alpha_trans: 1
autoreg_pq: 0
balance: 0
batch_size: 4
beta: 0.25
causal_gpt: 1
ckpt_dir: ../ckpts_panda/checkpoints/posegpt/generator2/checkpoints
ckpt_freq: 5
class_conditional: 1
class_freq: 100
concat_emb: 1
data_augment: 1
dataset_folder: ../
debug: 0
detailed_count: 0
dropout: 0.0
dummy: 0
dummy_data: 0
e_dim: 256
embed_every_step: 1
eos_force: 1
eval_classif: 0
eval_fid: 0
factor: 4
fid_freq: 40
fid_path: null
gen_eos: 0
gpt_attn_pdrop: 0.0
gpt_blocksize: 512
gpt_embd_pdrop: 0.0
gpt_nembd: 256
gpt_nhead: 4
gpt_nlayer: 8
gpt_resid_pdrop: 0.0
head_type: fc_wo_bias
heads: 4
hid_dim:
- 384
learning_rate: 1.0e-05
log_dir: ../ckpts_panda/checkpoints/posegpt/generator2
log_freq: 1000
mask_trans: 0
max_epochs: 600
min_window_sec: 2.0
model: poseGPT
n_codebook: 2
n_e: 512
n_iter_val: null
n_iters_per_epoch: 1000
n_layers:
- 0
- 6
n_train: 1000000
n_visu_to_save: 2
name: generator2
num_workers: 0
overfit: 0
pos_all: 1
pos_emb: scratch
pos_type: sine_frozen
pred_trans: 1
prefetch_factor: 2
pretrained_ckpt: ../ckpts_panda/checkpoints/posegpt/generator2/checkpoints/ckpt_60.pt
quant_epoch_max: 20
quant_min_prop: 1.0
restart_ckpt_freq: 4
sample_method: conv
sample_start: 1
save_dir: ../ckpts_panda/checkpoints/posegpt
seq_len: 96
seqlen_conditional: 1
seqlen_emb: scratch
train_data_dir: data/smplx/babel_trimmed/train_60/seqLen900_fps30_overlap0_minSeqLen16
use_amp: 0
val_data_dir: data/smplx/babel_trimmed/val_60/seqLen900_fps30_overlap0_minSeqLen16
val_dataset: h2o
val_freq: 2
val_split: test
val_view_id: 3
visu_freq: 200
visu_to_tboard: 0
vq_ckpt: ../ckpts_panda/checkpoints/posegpt/auto_encoder/checkpoints/ckpt_400.pt
vq_model: CausalVQVAE
