action_emb: scratch
alpha_body: null
alpha_root: null
alpha_trans: 1
autoreg_pq: 0
balance: 0
batch_size_factors:
- 1
- 1
- 2
beta: 0.25
causal_gpt: 1
ckpt_dir: ../ckpts_panda/checkpoints/posegpt/generator_tratrj565/checkpoints
ckpt_freq: 5
class_conditional: 1
class_freq: 100
classif_ckpt: null
classif_ckpt_babel: /scratch/1/user/tlucas/pose_generation/logs/publish_transformer_classif_lrx2/classification_TR/checkpoints/ckpt_fid.pt
concat_emb: 1
data_augment: 1
dataset_folder: ../
debug: 0
detailed_count: 0
dropout: 0.0
dummy: 0
dummy_data: 0
e_dim: 256
embed_every_step: 1
eos_force: 1
eval_classif: 0
eval_fid: 0
factor: 4
fid_freq: 40
gen_eos: 0
gpt_attn_pdrop: 0.2
gpt_blocksize: 512
gpt_embd_pdrop: 0.2
gpt_nembd: 256
gpt_nhead: 4
gpt_nlayer: 8
gpt_resid_pdrop: 0.2
head_type: fc_wo_bias
heads: 4
hid_dim:
- 384
learning_rate: 1.0e-05
log_dir: ../ckpts_panda/checkpoints/posegpt/generator_tratrj565
log_freq: 1000
mask_trans: 0
max_epochs: 600
model: poseGPT
n_codebook: 2
n_e: 512
n_iter_val: null
n_iters_per_epoch: 1000
n_layers:
- 0
- 6
n_train: 1000000
n_visu_to_save: 2
name: generator_tratrj565
num_workers: 0
overfit: 0
pos_all: 1
pos_emb: scratch
pos_type: sine_frozen
pred_trans: 1
prefetch_factor: 2
pretrained_ckpt: null
quant_epoch_max: 20
quant_min_prop: 1.0
restart_ckpt_freq: 4
sample_method: conv
sample_start: 1
save_dir: ../ckpts_panda/checkpoints/posegpt
seq_len: 256
seqlen_conditional: 1
seqlen_emb: scratch
train_batch_size: 32
train_data_dir: data/smplx/babel_trimmed/train_60/seqLen900_fps30_overlap0_minSeqLen16
train_datasets:
- h2o
- asshand
- ass101
train_splits:
- train
- train
- train
use_amp: 0
val_batch_size: 16
val_data_dir: data/smplx/babel_trimmed/val_60/seqLen900_fps30_overlap0_minSeqLen16
val_datasets:
- h2o
- asshand
val_freq: 2
val_splits:
- val
- val
visu_freq: 200
visu_to_tboard: 0
vq_ckpt: ../ckpts_panda/checkpoints/posegpt/autoencode_tratrj/checkpoints/ckpt_565.pt
vq_model: CausalVQVAE
